### ISSUE TITLE
Importing runtype breaks (at least) get_type_hints

### ISSUE THREAD

**Issue by apirogov** [erezsh/runtype#14]
Is runtype somehow messing with typing, typing_extensions or pydantic?

A thing that looks relevant in my logs is:

```python
/home/admin/.pyenv/versions/3.8.10/lib/python3.8/typing.py:1264: in get_type_hints
    value = _eval_type(value, globalns, localns)
/home/admin/.pyenv/versions/3.8.10/lib/python3.8/typing.py:270: in _eval_type
    return t._evaluate(globalns, localns)
E   TypeError: _evaluate() missing 1 required positional argument: '_'
```

Even just importing `runtype.validation` triggers that problem, so I'd expect it does some monkey patching on import.

**Comment by erezsh** [comment]
Thanks for letting me know!

I merged a fix to the `master` branch. Let me know if that helped.

**Comment by apirogov** [comment]
Yes, that resolved the issue, thanks!
