### ISSUE TITLE
Support Union for is_subtype

### ISSUE THREAD

**Issue by maurosilber** [erezsh/runtype#45]
Hi!

Thanks for creating this project! `is_subtype` should probably be part of `typing` or `typing_extensions`.

Currently, `is_subtype` does not work for Unions:

```python
>>> import runtype
>>> runtype.is_subtype(str, str | None)
True
>>> runtype.is_subtype(str | None, str | None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.10/site-packages/runtype/validation.py", line 30, in is_subtype
    return ct1 <= ct2
  File ".../python3.10/site-packages/runtype/pytypes.py", line 130, in __le__
    return issubclass(self.kernel, other.kernel)
TypeError: issubclass() arg 1 must be a class
```

Does it make sense to support this? I can try to add support for this feature.

In my project, I wanted to check that some Pydantic classes implement some Protocols. I cannot inherit from those Protocols, as both Pydantic and Protocol use (different) metaclasses. So I was comparing the `__annotations__` in the Protocol with the ones in the pydantic implementation using `is_subtype`.

Thanks!

**Comment by erezsh** [comment]
Hi @maurosilber ,

Thanks for reaching out.

This currently works for me in the master branch:

```python
>>> import runtype
>>> runtype.is_subtype(str | None, str | None)
True
```

Can you verify that it works for you too?

If so, I will try to make a new release soon.

> is_subtype should probably be part of typing or typing_extensions.

imho Python should just extend issubclass. They are already going in that direction, and now allow unions on the right side. It's just about completing that feature to support all types and all algebraic operations.

Anyway, I'm glad you found runtype useful! Maybe one day it could replace pydantic altogether ;)

**Comment by maurosilber** [comment]
Yes, it works from the master branch. Thanks!
