### ISSUE TITLE
`json` method doesn't work with list

### ISSUE THREAD

**Issue by wyfo** [erezsh/runtype#7]
As I wanted to add you to [apischema benchmark](https://wyfo.github.io/apischema/0.17/optimizations_and_benchmark/), I've noticed an issue with serialization, which simply doesn't work with list.

```python
from runtype import dataclass

@dataclass
class Bar:
    baz: int

@dataclass
class Foo:
    bars: list[Bar]

assert Foo([Bar(0)]).json() == {"bars": [Bar(baz=0)]}
```

As you can see, `Bar` instances are not serialized.

**Comment by erezsh** [comment]
Yes, you're right, it currently doesn't recurse into lists/dicts/sets/tuples.

I agree that would be the correct behavior.

**Comment by erezsh** [comment]
Fixed in `master`.

Thanks for reporting!
